version: '2'
 services:
   db:
     image: postgres
     ports:
       - "5432:5432"
   cache:
     image: redis
     ports:
       - "6379:6379"
   cms:
     build: ./wagtail-app
     command: python3 manage.py runserver 0.0.0.0:8000
     volumes:
       - ./wagtail-app:/usr/src/app
     ports:
       - "8000:8000"
     depends_on:
       - db
       - redis
   app:
     image: project-resources/ember-app
     ports:
       - "4200:4200"
     depends_on:
       - cms
